language: java
jdk:
  - oraclejdk8

before_install:
   - chmod +x gradlew

before_script:
  - chmod +x gradlew

script:
  - chmod +x ./gradlew
  - ./gradlew check
  - ./gradlew codeCoverageReport

test:
    post:
        - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
        - bash <(curl -s https://codecov.io/bash)

notification:
  email:
    - nemenkoma@gmail.com