language: java
jdk:
  - oraclejdk8

before_install:
   - chmod +x gradlew

before_script:
  - chmod +x gradlew

script:
  - chmod +x ./gradlew
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)

notification:
  email:
    - nemenkoma@gmail.com